server:
  port: 8080
spring:
  main:
    web-application-type: servlet
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    open-in-view: on
  datasource:
    url: jdbc:mysql://localhost:3306/employee+control
    username: root
    password:

      -